export interface DzikirItem {
  id: string;
  category: 'pagi' | 'petang' | 'doa-harian';
  title: string;
  textArabic: string;
  textLatin: string;
  translation: string;
  targetCount: number;
  source: string;
  benefit?: string;
  audioUrl?: string;
}

export const DZIKIR_PAGI_LIST: DzikirItem[] = [
  {
    id: 'pagi-1',
    category: 'pagi',
    title: '1. Ta\'awwudz Pembuka (3x)',
    textArabic: 'أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    textLatin: "A'ūżu billāhis-samī'il-'alīmi minasy-syaīṭānir-rajīm.",
    translation: 'Aku berlindung kepada Allah Yang Maha Mendengar lagi Maha Mengetahui dari godaan setan yang terkutuk.',
    targetCount: 3,
    source: 'Sunnah Pembuka Wirid Al-Matsurat',
  },
  {
    id: 'pagi-2',
    category: 'pagi',
    title: '2. Surah Al-Fatihah (1x)',
    textArabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ • الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ • الرَّحْمَٰنِ الرَّحِيمِ • مَالِكِ يَوْمِ الدِّينِ • إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ • اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ • صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
    textLatin: "Bismillāhir-raḥmānir-raḥīm. Al-ḥamdu lillāhi rabbil-'ālamīn. Ar-raḥmānir-raḥīm. Māliki yaumid-dīn...",
    translation: 'Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah, Tuhan semesta alam...',
    targetCount: 1,
    source: 'QS. Al-Fatihah: 1-7',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/001001.mp3',
  },
  {
    id: 'pagi-3',
    category: 'pagi',
    title: '3. Surah Al-Baqarah 1-5 (1x)',
    textArabic: 'الم • ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِلْمُتَّقِينَ • الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ • وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنْزِلَ إِلَيْكَ وَمَا أُنْزِلَ مِنْ قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ • أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ ۖ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ',
    textLatin: "Alif Lām Mīm. Żālikal-kitābu lā raiba fīhi hudal lil-muttaqīn...",
    translation: 'Alif Lam Mim. Kitab (Al-Qur\'an) ini tidak ada keraguan padanya; petunjuk bagi mereka yang bertakwa...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 1-5',
  },
  {
    id: 'pagi-4',
    category: 'pagi',
    title: '4. Surah Al-Baqarah 255 (Ayat Kursi)',
    textArabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    textLatin: "Allāhu lā ilāha illā huwal-ḥayyul-qayyūm, lā ta'khużuhū sinatuw wa lā naūm...",
    translation: 'Allah, tidak ada tuhan selain Dia. Yang Mahahidup, yang terus-menerus mengurus (makhluk-Nya)...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 255 & HR. An-Nasa\'i',
    benefit: 'Barangsiapa membacanya di pagi hari, ia dilindungi dari gangguan jin hingga petang hari.',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/002255.mp3',
  },
  {
    id: 'pagi-5',
    category: 'pagi',
    title: '5. Surah Al-Baqarah 256-257',
    textArabic: 'لَا إِكْرَاهَ فِي الدِّينِ ۖ قَدْ تَبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ ۚ فَمَنْ يَكْفُرْ بِالطَّاغُوتِ وَيُؤْمِنْ بِاللَّهِ فَقَدِ اسْتَمْسَكَ بِالْعُرْوَةِ الْوُثْقَىٰ لَا انْفِصَامَ لَهَا ۗ وَاللَّهُ سَمِيعٌ عَلِيمٌ',
    textLatin: "Lā ikrāha fid-dīni qad tabayyanar-rusydu minal-ghayy...",
    translation: 'Tidak ada paksaan dalam (menganut) agama (Islam); sungguh, telah jelas antara jalan yang benar dengan jalan yang sesat...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 256-257',
  },
  {
    id: 'pagi-6',
    category: 'pagi',
    title: '6. Surah Al-Baqarah 284-286 (Āmanar-Rasūlu)',
    textArabic: 'آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ • لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا...',
    textLatin: "Āmanar-rasūlu bimā unzila ilaihi mir rabbihī wal-mu'minūn...",
    translation: 'Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya dari Tuhannya, demikian pula orang-orang yang beriman...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 284-286 & HR. Bukhari',
    benefit: 'Dua ayat ini mencukupi pembacanya dari berbagai keburukan sepanjang hari/malam.',
  },
  {
    id: 'pagi-7',
    category: 'pagi',
    title: '7. Surah Al-Ikhlas (3x)',
    textArabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ • اللَّهُ الصَّمَدُ • لَمْ يَلِدْ وَلَمْ يُولَدْ • وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    textLatin: "Qul huwallāhu aḥad. Allāhuṣ-ṣamad. Lam yalid wa lam yūlad. Wa lam yakul lahū kufuwan aḥad.",
    translation: 'Katakanlah (Muhammad), "Dialah Allah, Yang Maha Esa. Allah tempat meminta segala sesuatu..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082 & Tirmidzi no. 3575',
    benefit: 'Mencukupi segala sesuatu dari berbagai keburukan sepanjang hari.',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112001.mp3',
  },
  {
    id: 'pagi-8',
    category: 'pagi',
    title: '8. Surah Al-Falaq (3x)',
    textArabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ • مِنْ شَرِّ مَا خَلَقَ • وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ • وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ • وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    textLatin: "Qul a'ūżu birabbil-falaq. Min syarri mā khalaq. Wa min syarri ghāsiqin iżā waqab...",
    translation: 'Katakanlah, "Aku berlindung kepada Tuhan yang menguasai subuh (fajar), dari kejahatan (makhluk yang) Dia ciptakan..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082 & Tirmidzi no. 3575',
    benefit: 'Perlindungan dari kejahatan sihir, dengki, dan malam.',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/113001.mp3',
  },
  {
    id: 'pagi-9',
    category: 'pagi',
    title: '9. Surah An-Nas (3x)',
    textArabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ • مَلِكِ النَّاسِ • إِلَٰهِ النَّاسِ • مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ • الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ • مِنَ الْجِنَّةِ وَالنَّاسِ',
    textLatin: "Qul a'ūżu birabbin-nās. Malikin-nās. Ilāhin-nās. Min syarril-waswāsil-khannās...",
    translation: 'Katakanlah, "Aku berlindung kepada Tuhannya manusia, Raja manusia, Sembahan manusia..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082 & Tirmidzi no. 3575',
    benefit: 'Perlindungan dari godaan bisikan jin dan manusia.',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/114001.mp3',
  },
  {
    id: 'pagi-10',
    category: 'pagi',
    title: '10. Asbaḥnā wa Asbaḥal-Mulku Lillāh',
    textArabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
    textLatin: "Asbaḥnā wa asbaḥal-mulku lillāhi wal-ḥamdu lillāhi, lā ilāha illallāhu waḥdahū lā syarīka lah...",
    translation: 'Kami telah memasuki waktu pagi dan kerajaan hanya milik Allah, segala puji bagi Allah...',
    targetCount: 1,
    source: 'HR. Muslim no. 2723',
  },
  {
    id: 'pagi-11',
    category: 'pagi',
    title: '11. Asbaḥnā \'Alā Fiṭratil-Islām',
    textArabic: 'أَصْبَحْنَا عَلَى فِطْرَةِ الْإِسْلَامِ وَعَلَى كَلِمَةِ الْإِخْلَاصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إِبْرَاهِيمَ حَنِيفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِينَ',
    textLatin: "Asbaḥnā 'alā fiṭratil-islām wa 'alā kalimatil-ikhlāṣ, wa 'alā dīni nabiyyinā muḥammadin ṣallallāhu 'alaihi wa sallam...",
    translation: 'Di waktu pagi kami memegang agama Islam, kalimat ikhlas, agama Nabi kami Muhammad ﷺ, dan agama bapak kami Ibrahim...',
    targetCount: 1,
    source: 'HR. Ahmad 3/406',
  },
  {
    id: 'pagi-12',
    category: 'pagi',
    title: '12. Doa Kesyukuran Kenikmatan (3x)',
    textArabic: 'اللَّهُمَّ إِنِّي أَصْبَحْتُ مِنْكَ فِي نِعْمَةٍ وَعَافِيَةٍ وَسِتْرٍ، فَأَتِمَّ عَلَيَّ نِعْمَتَكَ وَعَافِيَتَكَ وَسِتْرَكَ فِي الدُّنْيَا وَالْآخِرَةِ',
    textLatin: "Allāhumma innī asbaḥtu minka fī ni'matiw wa 'āfiyatiw wa sitr, fa atimma 'alayya ni'mataka wa 'āfiyataka wa sitraka fid-dunyā wal-ākhirah.",
    translation: 'Ya Allah, sesungguhnya aku di waktu pagi ini berada dalam kenikmatan, kesehatan, dan perlindungan dari-Mu. Maka sempurnakanlah nikmat-Mu...',
    targetCount: 3,
    source: 'HR. Ibnun Sunni no. 55',
  },
  {
    id: 'pagi-13',
    category: 'pagi',
    title: '13. Doa Pujian Nikmat Pagi',
    textArabic: 'اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ',
    textLatin: "Allāhumma mā asbaḥa bī min ni'matin au bi aḥadim min khalqika fa minka waḥdaka lā syarīka lak, fa lakal-ḥamdu wa lakasy-syukr.",
    translation: 'Ya Allah, nikmat apa pun yang ada padaku atau pada salah seorang dari makhluk-Mu di pagi ini adalah dari-Mu semata...',
    targetCount: 1,
    source: 'HR. Abu Dawud no. 5073',
  },
  {
    id: 'pagi-14',
    category: 'pagi',
    title: '14. Yā Rabbi Lakal-Ḥamdu (3x)',
    textArabic: 'يَا رَبِّ لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ وَلِعَظِيمِ سُلْطَانِكَ',
    textLatin: "Yā rabbi lakal-ḥamdu kamā yanbaghī lijalāli wajhika wa li'aẓīmi sulṭānik.",
    translation: 'Wahai Tuhanku, bagi-Mu segala puji sebagaimana yang layak bagi keagungan wajah-Mu dan kebesaran kekuasaan-Mu.',
    targetCount: 3,
    source: 'HR. Ibnu Majah no. 3801',
    benefit: 'Dua malaikat kewalahan mencatat pahala pujian ini.',
  },
  {
    id: 'pagi-15',
    category: 'pagi',
    title: '15. Kerelaan Hati kepada Allah, Islam, & Nabi (3x)',
    textArabic: 'رَضِيتُ بِاللَّهِ رَبًّا وَبِالْإِسْلَامِ دِينًا وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا وَرَسُولًا',
    textLatin: "Raḍītu billāhi rabbā, wa bil-islāmi dīnā, wa bi muḥammadin ṣallallāhu 'alaihi wa sallama nabiyyaw wa rasūlā.",
    translation: 'Aku ridha Allah sebagai Tuhanku, Islam sebagai agamaku, dan Nabi Muhammad ﷺ sebagai Nabiku.',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5072',
    benefit: 'Allah menjamin akan meridhainya pada hari kiamat kelak.',
  },
  {
    id: 'pagi-16',
    category: 'pagi',
    title: '16. Subḥānallāhi wa Biḥamdihī \'Adada Khalqih (3x)',
    textArabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ',
    textLatin: "Subḥānallāhi wa biḥamdihī, 'adada khalqihī wa riḍā nafsihī wa zinata 'arsyihī wa midāda kalimātih.",
    translation: 'Maha Suci Allah dan dengan memuji-Nya, sebanyak bilangan makhluk-Nya, keridhaan diri-Nya, perhiasan \'Arsy-Nya, dan tinta kalimat-kalimat-Nya.',
    targetCount: 3,
    source: 'HR. Muslim no. 2726',
    benefit: 'Pahala tasbih ini menimbangi zikir dari subuh hingga dhuha.',
  },
  {
    id: 'pagi-17',
    category: 'pagi',
    title: '17. Bismillāhillażī Lā Yaḍurru (3x)',
    textArabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    textLatin: "Bismillāhillażī lā yaḍurru ma'asmihī syai'un fil-arḍi wa lā fis-samā'i wa huwas-samī'ul-'alīm.",
    translation: 'Dengan nama Allah yang bila disebut, segala sesuatu di bumi dan di langit tidak akan berbahaya. Dialah Yang Maha Mendengar lagi Maha Mengetahui.',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5088',
    benefit: 'Tidak akan marabahaya yang memudaratkan sepanjang hari.',
  },
  {
    id: 'pagi-18',
    category: 'pagi',
    title: '18. Doa Perlindungan dari Syirik (3x)',
    textArabic: 'اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ',
    textLatin: "Allāhumma innā na'ūżu bika min an nusyrika bika syai'an na'lamuh, wa nastaghfiruka limā lā na'lamuh.",
    translation: 'Ya Allah, sesungguhnya kami berlindung kepada-Mu dari menyekutukan-Mu dengan sesuatu yang kami ketahui, dan kami memohon ampunan-Mu atas apa yang tidak kami ketahui.',
    targetCount: 3,
    source: 'HR. Ahmad 4/403',
  },
  {
    id: 'pagi-19',
    category: 'pagi',
    title: '19. A\'ūżu Bikalimātillāhit-Tāmmāt (3x)',
    textArabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    textLatin: "A'ūżu bikalimātillāhit-tāmmāti min syarri mā khalaq.",
    translation: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang diciptakan-Nya.',
    targetCount: 3,
    source: 'HR. Muslim no. 2709',
  },
  {
    id: 'pagi-20',
    category: 'pagi',
    title: '20. Doa Pelindung Kesusahan & Beban Utang (3x)',
    textArabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
    textLatin: "Allāhumma innī a'ūżu bika minal-hammi wal-ḥazan, wa a'ūżu bika minal-'ajzi wal-kasal...",
    translation: 'Ya Allah, aku berlindung kepada-Mu dari keluh kesah dan duka cita, dari rasa lemah dan malas, dari sifat penakut dan kikir, serta dari lilitan utang dan tekanan orang-orang.',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 1555',
    benefit: 'Allah akan menghilangkan duka cita dan melunaskan utang-utangnya.',
  },
  {
    id: 'pagi-21',
    category: 'pagi',
    title: '21. Doa Kesehatan Badan, Pendengaran, & Penglihatan (3x)',
    textArabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ',
    textLatin: "Allāhumma 'āfinī fī badanī, Allāhumma 'āfinī fī sam'ī, Allāhumma 'āfinī fī baṣarī, lā ilāha illā anta.",
    translation: 'Ya Allah, berikanlah kesehatan pada badanku. Ya Allah, berikanlah kesehatan pada pendengaranku. Ya Allah, berikanlah kesehatan pada penglihatanku, tidak ada tuhan selain Engkau.',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5090',
  },
  {
    id: 'pagi-22',
    category: 'pagi',
    title: '22. Doa Perlindungan dari Kekufuran & Fakir (3x)',
    textArabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، لَا إِلَٰهَ إِلَّا أَنْتَ',
    textLatin: "Allāhumma innī a'ūżu bika minal-kufri wal-faqr, wa a'ūżu bika min 'ażābil-qabr, lā ilāha illā anta.",
    translation: 'Ya Allah, sesungguhnya aku berlindung kepada-Mu dari kekufuran dan kefakiran, dan aku berlindung kepada-Mu dari azab kubur, tidak ada tuhan selain Engkau.',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5090',
  },
  {
    id: 'pagi-23',
    category: 'pagi',
    title: '23. Ḥasbiyallāhu Lā Ilāha Illā Huwa (7x)',
    textArabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    textLatin: "Ḥasbiyallāhu lā ilāha illā huwa, 'alaihi tawakkaltu, wa huwa rabbul-'arsyil-'aẓīm.",
    translation: 'Cukuplah Allah bagiku; tidak ada tuhan selain Dia. Hanya kepada-Nya aku bertawakal, dan Dia adalah Tuhan yang memiliki \'Arsy yang agung.',
    targetCount: 7,
    source: 'QS. At-Taubah: 129 & HR. Abu Dawud no. 5081',
    benefit: 'Allah akan mencukupi apa yang menjadi kesusahan dunia dan akhiratnya.',
  },
  {
    id: 'pagi-24',
    category: 'pagi',
    title: '24. Sayyidul Istighfar (Rajanya Istighfar)',
    textArabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    textLatin: 'Allāhumma anta rabbī lā ilāha illā anta khalaqtanī wa ana \'abduka wa ana \'alā \'ahdika wa wa\'dika mastata\'tu...',
    translation: 'Ya Allah, Engkau adalah Tuhanku, tidak ada tuhan selain Engkau. Engkau yang menciptakanku dan aku adalah hamba-Mu...',
    targetCount: 1,
    source: 'HR. Bukhari no. 6306',
    benefit: 'Barangsiapa membacanya di pagi hari lalu meninggal hari itu, ia tergolong penghuni surga.',
  },
  {
    id: 'pagi-25',
    category: 'pagi',
    title: '25. Doa Keselamatan Diri & Keluarga',
    textArabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي',
    textLatin: "Allāhumma innī as'alukal-'afwa wal-'āfiyata fid-dunyā wal-ākhirah, Allāhumma innī as'alukal-'afwa wal-'āfiyata fī dīnī wa dunyāya wa ahlī wa mālī...",
    translation: 'Ya Allah, sesungguhnya aku memohon ampunan dan keselamatan di dunia dan akhirat. Ya Allah, aku memohon keselamatan dalam agamaku, duniaku, keluargaku, dan hartaku...',
    targetCount: 1,
    source: 'HR. Abu Dawud no. 5074',
  },
  {
    id: 'pagi-26',
    category: 'pagi',
    title: '26. Subḥānallāhi wa Biḥamdih (100x)',
    textArabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    textLatin: "Subḥānallāhi wa biḥamdih.",
    translation: 'Maha Suci Allah dan dengan memuji-Nya.',
    targetCount: 100,
    source: 'HR. Muslim no. 2692',
    benefit: 'Dihapuskan dosa-dosanya walaupun sebanyak buih di lautan.',
  },
  {
    id: 'pagi-27',
    category: 'pagi',
    title: '27. Astaghfirullāh wa Atūbu Ilaih (100x)',
    textArabic: 'أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ',
    textLatin: "Astaghfirullāha wa atūbu ilaih.",
    translation: 'Aku memohon ampun kepada Allah dan bertobat kepada-Nya.',
    targetCount: 100,
    source: 'HR. Bukhari no. 6307 & Muslim no. 2702',
  },
  {
    id: 'pagi-28',
    category: 'pagi',
    title: '28. Sholawat Kepada Nabi Muhammad ﷺ (10x)',
    textArabic: 'اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ',
    textLatin: "Allāhumma ṣalli 'alā sayyidinā muḥammadin wa 'alā āli sayyidinā muḥammad.",
    translation: 'Ya Allah, limpahkanlah sholawat kepada junjungan kami Nabi Muhammad dan kepada keluarga Nabi Muhammad.',
    targetCount: 10,
    source: 'HR. At-Tabarani',
  },
  {
    id: 'pagi-29',
    category: 'pagi',
    title: '29. Doa Rābiṭah (Penutup Al-Matsurat)',
    textArabic: 'اللَّهُمَّ إِنَّكَ تَعْلَمُ أَنَّ هَذِهِ الْقُلُوبَ قَدِ اجْتَمَعَتْ عَلَى مَحَبَّتِكَ، وَالْتَقَتْ عَلَى طَاعَتِكَ، وَتَوَحَّدَتْ عَلَى دَعْوَتِكَ، وَتَعَاهَدَتْ عَلَى نُصْرَةِ شَرِيعَتِكَ، فَوَثِّقِ اللَّهُمَّ رَابِطَتَهَا، وَأَدِمْ وُدَّهَا، وَاهْدِهَا سُبُلَهَا',
    textLatin: "Allāhumma innaka ta'lamu anna hāżihil-qulūba qadijtama'at 'alā maḥabbatik, wal-taqat 'alā ṭā'atik...",
    translation: 'Ya Allah, sesungguhnya Engkau mengetahui bahwa hati-hati ini telah berkumpul atas dasar kecintaan kepada-Mu, bertemu dalam ketaatan kepada-Mu, dan bersatu dalam dakwah-Mu. Maka ikatkanlah ikatannya ya Allah...',
    targetCount: 1,
    source: 'Al-Matsurat Hasan Al-Banna',
    benefit: 'Mempererat tali ukhuwah persaudaraan karena Allah.',
  },
];

export const DZIKIR_PETANG_LIST: DzikirItem[] = [
  {
    id: 'petang-1',
    category: 'petang',
    title: '1. Ta\'awwudz Pembuka (3x)',
    textArabic: 'أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    textLatin: "A'ūżu billāhis-samī'il-'alīmi minasy-syaīṭānir-rajīm.",
    translation: 'Aku berlindung kepada Allah Yang Maha Mendengar lagi Maha Mengetahui dari godaan setan yang terkutuk.',
    targetCount: 3,
    source: 'Sunnah Pembuka Wirid Al-Matsurat',
  },
  {
    id: 'petang-2',
    category: 'petang',
    title: '2. Surah Al-Fatihah (1x)',
    textArabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ • الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ...',
    textLatin: "Bismillāhir-raḥmānir-raḥīm. Al-ḥamdu lillāhi rabbil-'ālamīn...",
    translation: 'Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Segala puji bagi Allah...',
    targetCount: 1,
    source: 'QS. Al-Fatihah: 1-7',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/001001.mp3',
  },
  {
    id: 'petang-3',
    category: 'petang',
    title: '3. Surah Al-Baqarah 1-5 (1x)',
    textArabic: 'الم • ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِلْمُتَّقِينَ...',
    textLatin: "Alif Lām Mīm. Żālikal-kitābu lā raiba fīhi hudal lil-muttaqīn...",
    translation: 'Alif Lam Mim. Kitab (Al-Qur\'an) ini tidak ada keraguan padanya...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 1-5',
  },
  {
    id: 'petang-4',
    category: 'petang',
    title: '4. Surah Al-Baqarah 255 (Ayat Kursi)',
    textArabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ...',
    textLatin: "Allāhu lā ilāha illā huwal-ḥayyul-qayyūm...",
    translation: 'Allah, tidak ada tuhan selain Dia. Yang Mahahidup...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 255 & HR. An-Nasa\'i',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/002255.mp3',
  },
  {
    id: 'petang-5',
    category: 'petang',
    title: '5. Surah Al-Baqarah 284-286 (Āmanar-Rasūlu)',
    textArabic: 'آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ...',
    textLatin: "Āmanar-rasūlu bimā unzila ilaihi mir rabbihī wal-mu'minūn...",
    translation: 'Rasul (Muhammad) beriman kepada apa yang diturunkan kepadanya dari Tuhannya...',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 284-286',
  },
  {
    id: 'petang-6',
    category: 'petang',
    title: '6. Surah Al-Ikhlas (3x)',
    textArabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ • اللَّهُ الصَّمَدُ • لَمْ يَلِدْ وَلَمْ يُولَدْ • وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
    textLatin: "Qul huwallāhu aḥad. Allāhuṣ-ṣamad...",
    translation: 'Katakanlah (Muhammad), "Dialah Allah, Yang Maha Esa..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112001.mp3',
  },
  {
    id: 'petang-7',
    category: 'petang',
    title: '7. Surah Al-Falaq (3x)',
    textArabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ • مِنْ شَرِّ مَا خَلَقَ...',
    textLatin: "Qul a'ūżu birabbil-falaq. Min syarri mā khalaq...",
    translation: 'Katakanlah, "Aku berlindung kepada Tuhan yang menguasai subuh..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/113001.mp3',
  },
  {
    id: 'petang-8',
    category: 'petang',
    title: '8. Surah An-Nas (3x)',
    textArabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ • مَلِكِ النَّاسِ • إِلَٰهِ النَّاسِ...',
    textLatin: "Qul a'ūżu birabbin-nās. Malikin-nās...",
    translation: 'Katakanlah, "Aku berlindung kepada Tuhannya manusia..."',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5082',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/114001.mp3',
  },
  {
    id: 'petang-9',
    category: 'petang',
    title: '9. Amsainā wa Amsal-Mulku Lillāh',
    textArabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ...',
    textLatin: "Amsainā wa amsal-mulku lillāhi wal-ḥamdu lillāh...",
    translation: 'Kami telah memasuki waktu petang dan kerajaan hanya milik Allah...',
    targetCount: 1,
    source: 'HR. Muslim no. 2723',
  },
  {
    id: 'petang-10',
    category: 'petang',
    title: '10. Sayyidul Istighfar (Petang)',
    textArabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ...',
    textLatin: 'Allāhumma anta rabbī lā ilāha illā anta khalaqtanī...',
    translation: 'Ya Allah, Engkau adalah Tuhanku, tidak ada tuhan selain Engkau...',
    targetCount: 1,
    source: 'HR. Bukhari no. 6306',
  },
  {
    id: 'petang-11',
    category: 'petang',
    title: '11. Doa Perlindungan dari Kejahatan Malam (3x)',
    textArabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    textLatin: "A'ūżu bikalimātillāhit-tāmmāti min syarri mā khalaq.",
    translation: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari kejahatan makhluk yang diciptakan-Nya.',
    targetCount: 3,
    source: 'HR. Muslim no. 2709',
  },
  {
    id: 'petang-12',
    category: 'petang',
    title: '12. Bismillāhillażī Lā Yaḍurru (3x)',
    textArabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    textLatin: "Bismillāhillażī lā yaḍurru ma'asmihī syai'un...",
    translation: 'Dengan nama Allah yang bila disebut, segala sesuatu di bumi dan di langit tidak akan berbahaya...',
    targetCount: 3,
    source: 'HR. Abu Dawud no. 5088',
  },
  {
    id: 'petang-13',
    category: 'petang',
    title: '13. Sholawat Kepada Nabi Muhammad ﷺ (10x)',
    textArabic: 'اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِ سَيِّدِنَا مُحَمَّدٍ',
    textLatin: "Allāhumma ṣalli 'alā sayyidinā muḥammad...",
    translation: 'Ya Allah, limpahkanlah sholawat kepada junjungan kami Nabi Muhammad.',
    targetCount: 10,
    source: 'HR. At-Tabarani',
  },
  {
    id: 'petang-14',
    category: 'petang',
    title: '14. Doa Rābiṭah (Penutup Petang)',
    textArabic: 'اللَّهُمَّ إِنَّكَ تَعْلَمُ أَنَّ هَذِهِ الْقُلُوبَ قَدِ اجْتَمَعَتْ عَلَى مَحَبَّتِكَ...',
    textLatin: "Allāhumma innaka ta'lamu anna hāżihil-qulūba...",
    translation: 'Ya Allah, sesungguhnya Engkau mengetahui bahwa hati-hati ini telah berkumpul...',
    targetCount: 1,
    source: 'Al-Matsurat Hasan Al-Banna',
  },
];

export const DOA_HARIAN_LIST: DzikirItem[] = [
  {
    id: 'doa-1',
    category: 'doa-harian',
    title: 'Doa Sebelum Tidur',
    textArabic: 'بِاسْمِكَ اللَّهُمَّ أَحْيَا وَأَمُوتُ',
    textLatin: "Bismikallāhumma aḥyā wa amūt.",
    translation: 'Dengan nama-Mu ya Allah aku hidup dan dengan nama-Mu aku mati.',
    targetCount: 1,
    source: 'HR. Bukhari no. 6312 & Muslim no. 2711',
  },
  {
    id: 'doa-2',
    category: 'doa-harian',
    title: 'Doa Bangun Tidur',
    textArabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    textLatin: "Al-ḥamdu lillāhillażī aḥyānā ba'da mā amātanā wa ilaihin-nusyūr.",
    translation: 'Segala puji bagi Allah yang telah menghidupkan kami setelah mematikan kami, dan kepada-Nya kami dibangkitkan.',
    targetCount: 1,
    source: 'HR. Bukhari no. 6312',
  },
  {
    id: 'doa-3',
    category: 'doa-harian',
    title: 'Doa Keluar Rumah',
    textArabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    textLatin: "Bismillāhi tawakkaltu 'alallāh, lā ḥaula wa lā quwwata illā billāh.",
    translation: 'Dengan nama Allah, aku bertawakal kepada Allah, tidak ada daya dan kekuatan kecuali dengan pertolongan Allah.',
    targetCount: 1,
    source: 'HR. Abu Dawud no. 5095 & Tirmidzi no. 3426',
  },
  {
    id: 'doa-4',
    category: 'doa-harian',
    title: 'Doa Masuk Masjid',
    textArabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    textLatin: "Allāhummaftaḥ lī abwāba raḥmatik.",
    translation: 'Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.',
    targetCount: 1,
    source: 'HR. Muslim no. 713',
  },
  {
    id: 'doa-5',
    category: 'doa-harian',
    title: 'Doa Kebaikan Dunia & Akhirat (Sapu Jagat)',
    textArabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    textLatin: "Rabbanā ātinā fid-dunyā ḥasanataw wa fil-ākhirati ḥasanataw wa qinā 'ażāban-nār.",
    translation: 'Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan lindungilah kami dari azab neraka.',
    targetCount: 1,
    source: 'QS. Al-Baqarah: 201 & HR. Bukhari no. 4522',
  },
];
